apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-postgr-deployment
  namespace: stpk-short
spec:
  replicas: 1
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: short-postgr
          image: postgres:16
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
