kind: Service
apiVersion: v1
metadata:
  name: postgres-ClusterIP
  namespace: stpk-short
spec:
  selector:
    components: postgres
  type:  ClusterIP
  ports:
  - name:  postgres-port
    port:  5432
    targetPort: 5432