apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-postgr-deployment
  namespace: stpk-short
spec:
  replicas: 1
  selector:
    matchLabels:
      components: postgress
  template:
    metadata:
      labels:
        components: postgress
    spec:
      containers:
        - name: postgress
          image: postgres:16
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
