namespace: stpk-short #default namespace for that course deployment
env: production

# APP VALUES
app: 
  name: short-app
  replicaCount: 1
  components: frontend
  image: 
    name: antonlarichev/short-app
    version: v1.4
  port: 80
  limits:
    memory: "128Mi"
    cpu: "500m"

# API VALUES
api:
  name: short-api
  replicaCount: 1
  components: api
  image: 
    name: antonlarichev/short-api
    version: v1.0
  port: 3000
  limits:
    memory: "128Mi"
    cpu: "500m"
  envs: 
  - DATABASE_URL

#POSTGRES VALUES
postgres: 
  name: postgres
  component: postgres
  image:
    name: postgres
    version: 16.0
  port: 5432
  limits:
    memory: "512Mi"
    cpu: "500m"
  volumes:
  envs:
  - POSTGRES_DB
  - POSTGRES_USER
  - POSTGRES_PASSWORD
db:
  user: demo
  password: demo
  db: demo
