apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-clusterip:%d/%s" 
  .Values.db.user 
  .Values.db.password 
  .Values.postgres.name 
  (.Values.postgres.port | int64 ) 
  .Values.db.db | b64enc | quote }}

  # cG9zdGdyZXNxbDovL2RlbW86ZGVtb0Bwb3N0Z3Jlcy1jbHVzdGVyaXA6NTQzMi9kZW1v