kind: Service
apiVersion: v1
metadata:
  name:  {{ .Values.app.name}}-clusterip
  namespace: {{ .Values.namespace }}
spec:
  selector:
    components: {{ .Values.app.components }}
  type:  ClusterIP
  ports:
  - name:  cluster-port
    port:  {{ .Values.app.port }}
    protocol: TCP