
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  lables: {{- include "chart.lables" . | indent 4}}
  namespace: {{ .Values.namespace }}
data:
  {{- if eq .Values.env "production" }} 
  paymentToken: "1234" 
  {{- else }}
  paymentToken: false
  {{- end }}