apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.postgres.name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
